# Site settings
title: Technology Action Project
email: team@techaction.io
url: https://techaction.io
description: "Technology Action Project provides information security consulting services, on a grant funded basis, for grassroots political collectives, groups and organizations."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#00ffff'
  black: '#23201d'
  whie: '#eeeeee'

font:
  serif: '"Playfair Display", serif'
  sans-serif: '"Barlow", sans-serif'

# Footer settings
footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  # - title: twitter
  #   url: https://twitter.com/SBootstrap
  # - title: facebook
  #   url:
  # - title: stack-overflow
  #   url: http://stackoverflow.com/questions/tagged/jekyll
  # - title: bitbucket
  #   url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/techaction

# Build settings
markdown: kramdown
permalink: pretty
